config/routes.rb
Rails.application.routes.draw do
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homepage#index"

  get 'db', to: "homepage#show"
  get 'download', to: "homepage#download_json"
  get 'seed_spreadsheets', to: "settings#seed_spreadsheets"
  get 'settings', to: "settings#index"
  post 'upload', to: "settings#upload", as: :upload
  get 'seed_assets', to: "settings#seed_assets", as: :seed_assets

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :project
  serialize :sizes, ActiveRecord::Coders::NestedHstore

  names = ["drawable-mdpi", "drawable-hdpi", "drawable-xhdpi", "drawable-xxhdpi", "drawable-xxxhdpi", "drawable-sw600dp-ldpi", "drawable-sw600dp-mdpi", "drawable-sw600dp-hdpi", "drawable-sw600dp-xhdpi", "drawable-sw720dp-ldpi", "drawable-sw720dp-mdpi", "drawable-sw720dp-hdpi", "drawable-sw720dp-xhdpi"]

  def calculate_correct_size
    ratio = {
      "drawable-mdpi" => 1, "drawable-hdpi" => 1.5, "drawable-xhdpi" => 2, "drawable-xxhdpi" => 3, "drawable-xxxhdpi" => 4, "drawable-sw600dp-ldpi" => 0.75, "drawable-sw600dp-mdpi" => 1, "drawable-sw600dp-hdpi" => 1.5, "drawable-sw600dp-xhdpi" => 2, "drawable-sw720dp-ldpi" => 0.75, "drawable-sw720dp-mdpi" => 1, "drawable-sw720dp-hdpi" => 1.5, "drawable-sw720dp-xhdpi" => 2
    }

    unless sizes["drawable-mdpi"].nil?
      sizes.each do |name, properties|
        if ratio.keys.include?(name)
          #for phones
          if name.match("drawable-[a-z]{3,}")
            mdpi_w = sizes["drawable-mdpi"]["width"]
            mdpi_h = sizes["drawable-mdpi"]["height"]
          #for tablets 7"
          elsif name.match("drawable-sw600dp")
            mdpi_w = sizes["drawable-sw600dp-mdpi"].nil? ? sizes["drawable-mdpi"]["width"] : sizes["drawable-sw600dp-mdpi"]["width"]
            mdpi_h = sizes["drawable-sw600dp-mdpi"].nil? ? sizes["drawable-mdpi"]["height"] : sizes["drawable-sw600dp-mdpi"]["height"]
          #for tablets 10"
          elsif name.match("drawable-sw720dp")
            mdpi_w = sizes["drawable-sw720dp-mdpi"].nil? ? sizes["drawable-mdpi"]["width"] : sizes["drawable-sw720dp-mdpi"]["width"]
            mdpi_h = sizes["drawable-sw720dp-mdpi"].nil? ? sizes["drawable-mdpi"]["height"] : sizes["drawable-sw720dp-mdpi"]["height"]
          end
        properties['correct'] = is_correct?(properties["width"], properties["height"], mdpi_w, mdpi_h, ratio[name])
        end
      end
    save!
    end
  end


  def is_correct?(asset_w, asset_h, mdpi_w, mdpi_h, ratio)
    correct = [
      (mdpi_w * ratio - mdpi_w * 0.15 < asset_w),
      (asset_w < mdpi_w * ratio + mdpi_w * 0.15),
      (mdpi_h * ratio - mdpi_h * 0.15 < asset_h),
      (asset_h < mdpi_h * ratio + mdpi_h * 0.15)
    ].all?
  end

end
=begin
size.update(correct: false, hint: "-10%: #{mdpi_w * ratio - mdpi_w * 0.1}x#{mdpi_h * ratio - mdpi_h * 0.1}
0: #{mdpi_w * ratio}x#{mdpi_h * ratio}
+10%: #{mdpi_w * ratio + mdpi_w * 0.1}x#{mdpi_h * ratio + mdpi_h * 0.1}")
puts 'hint was added'
=end

app/models/project.rb
class Project < ApplicationRecord
  has_many :assets, dependent: :destroy
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :asset

end

app/models/spreadsheet.rb
class Spreadsheet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :set_spreadsheet, :except => [:index, :refresh_db]

  def index
    @spreadsheets = Spreadsheet.all
  end

  def show
    @spreadsheet
  end

  def download_json
    @spreadsheet

    source = @spreadsheet.rows
    headers = source[0]

    to_json = []
    source[1..source.count].each do |row|
      hash = {}
      row.each_with_index do |v, i|
        hash[headers[i].to_sym] = v
      end
      to_json.push(hash)
    end

    filename = "#{@spreadsheet.title}_#{Date.today.strftime('%m_%d_%Y')}"
    File.open("#{Rails.root}/public/#{filename}.json","w") do |file|
      file.puts JSON.pretty_generate('rows' => to_json)
    end

    send_file "#{Rails.root}/public/#{filename}.json"
  end

  private
  def set_spreadsheet
    @spreadsheet = Spreadsheet.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @headers = %w(name mdpi hdpi xhdpi xxhdpi xxxhdpi sw600dp-ldpi sw600dp-mdpi sw600dp-hdpi sw600dp-xhdpi sw720dp-ldpi sw720dp-mdpi sw720dp-hdpi sw720dp-xhdpi)
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  require 'csv'
  require 'dropbox_sdk'
  before_action :dropbox_auth, only: [:index, :upload]

  def index
    @last_upload = @dropbox_client.search('/','.csv').last["modified"].to_time.in_time_zone("Kyiv").strftime("%a, %d %b %Y %T")
  end

  def upload
    #upload file to Dropbox
    @dropbox_client.put_file(params[:upload][:file].original_filename, params[:upload][:file].tempfile)
    flash[:notice] = "File uploaded"
    redirect_to "/settings"
  end

  def seed_spreadsheets
    SeedSpreadsheetsJob.perform_later
    redirect_to "/settings"
  end

  def seed_assets
    SeedAssetsJob.perform_later
    redirect_to root_path
  end

  private

  def dropbox_auth
    access_token = 'LeBsNFZ4OQkAAAAAAAArRMJWrd5Ag2K1SI28kEyzgbPKslbCufOAjXp73RArOqkI'
    @dropbox_client = DropboxClient.new(access_token)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csvs_helper.rb
module CsvsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/homepage/index.slim
h1 List of applications

ul
  - @spreadsheets.each do |sheet|    
    li 
      == link_to "DB of #{sheet.title}", {:controller => "homepage", :action => "show", :id => sheet.id }

app/views/homepage/show.slim
h1  DB

== link_to "Back", root_path
  
table.table.table-striped.table-hover style="width:70%"
  thead
    tr
      - @spreadsheet.rows[0].each do |header|
        th
          == header
  tbody
    - @spreadsheet.rows[1..@spreadsheet.rows.count].each do |row|
      tr
        - row.each do |cell|
          td 
            == cell

== link_to "Download json", {:controller => "homepage", :action => "download_json", :id => @spreadsheet.id }, class: "btn btn-primary btn-lg"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FC Tools</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/projects/index.slim
h1 List of projects

ul
  - @projects.each do |project|
    li 
      == link_to project.title, project_path(project)
  
  

app/views/projects/show.slim
h1 
  == "#{@project.title}. List of assets"
  
table.table.table-striped.table-hover style="width:75%"
  thead
    tr
      - @headers.each do |header|
        th
          == header
  tbody    
    - @project.assets.order(:name).each do |asset|
      tr  
        td
          == asset.name
        - @headers[1..@headers.count].each do |header|
          td class="size #{asset.sizes["drawable-#{header}"]['correct'] == false ? 'danger' : 'success' unless asset.sizes["drawable-#{header}"].nil?}"
            == asset.sizes["drawable-#{header}"].nil? ? "n/a" : "#{asset.sizes["drawable-#{header}"]['width']}x#{asset.sizes["drawable-#{header}"]['height']}"

app/views/settings/index.slim
h1 Settings

h2 Update databases
== link_to "Update database", seed_spreadsheets_path, class: "btn btn-primary"

h2 Update assets metadata
p File was uploaded at "#{@last_upload}"

p You need exiftool for this process
ul
  li Open Dropbox folder in teminal
  li run command "exiftool -f -r -p '$directory, $filename, $ImageWidth, $ImageHeight, $MIMEType' ./ > out.csv"
  li upload generated file to this section

== form_tag upload_path, { :multipart => true } do
    == file_field_tag 'upload[file]'
    == submit_tag "Upload"

h3 Seed assets
== link_to "Seed", seed_assets_path, class: "btn btn-primary"

app/views/shared/_navbar.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
      a.navbar-brand href="/"  FlashCardsTools
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          a href="/" DB            
        li
          a href="/projects" Assets
        li
          a href="/settings" Settings